# Generated by Django 3.1.2 on 2021-05-18 11:07

from django.db import migrations, models
import django_mysql.models
import test_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration_in_sec', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(validators=[test_app.models.validate_date])),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_in_sec', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(validators=[test_app.models.validate_date])),
                ('host', models.CharField(max_length=100)),
                ('participants', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1010, size=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_in_sec', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(validators=[test_app.models.validate_date])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
