# Generated by Django 3.1.2 on 2021-05-05 06:40

from django.db import migrations, models
import test_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration_in_sec', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(validators=[test_app.models.validate_date])),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('song_duration_in_sec', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(validators=[test_app.models.validate_date])),
                ('host', models.CharField(max_length=100)),
                ('participants', models.CharField(max_length=1012)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_in_sec', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(validators=[test_app.models.validate_date])),
            ],
        ),
    ]
