# Generated by Django 3.2.1 on 2021-05-06 12:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20210505_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1010, size=10),
        ),
    ]
